"""Second pass: provenance.json written by the stage13 documentation backfill names no provider. Resolve such
folders from the acquisition worker that writes them (git-tracked _scripts/workers/*.py mentioning the folder)
and the host of the URL that worker calls. Evidence is recorded; nothing is inferred from a folder name."""
import json, re, subprocess, sys, collections
IN, OUT = sys.argv[1], sys.argv[2]
doc = json.load(open(IN))
workers = [p for p in subprocess.run(["git", "ls-files", "_scripts/workers"], capture_output=True, text=True).stdout.split("\n") if p.endswith(".py")]
src = {w: subprocess.run(["git", "show", f"HEAD:{w}"], capture_output=True, text=True).stdout for w in workers}
cache = {}
def evidence_for(folder):
    if folder in cache:
        return cache[folder]
    parts = folder.split("/")
    hits = []
    for k in range(len(parts), 1, -1):
        pref = "/".join(parts[:k])
        hits = [w for w, s in src.items() if pref in s]
        if hits:
            break
    if not hits and len(parts) >= 2:
        # path built from separate literals, e.g. ROOT / "alternative_data" / "cryptoquant"
        pat = re.compile(r'"%s"\s*/\s*"%s"' % (re.escape(parts[0]), re.escape(parts[1])))
        hits = [w for w, s in src.items() if pat.search(s)]
        writers = [w for w in hits if re.search(r'OUT(_DIR)?\s*=\s*ROOT\s*/\s*' + pat.pattern, src[w])]
        if writers:
            hits = writers          # the worker that WRITES the folder, not one that merely reads it
    hosts = set()
    for w in hits:
        hosts |= set(re.findall(r"https?://([A-Za-z0-9.\-]+)", src[w]))
    hosts = sorted(h for h in hosts if "github" not in h and "localhost" not in h)
    cache[folder] = (hits, hosts)
    return cache[folder]
for r in doc["rows"]:
    if r["source_provider"] != "autogenerated_stage13_doc_backfill":
        continue
    hits, hosts = evidence_for(r["source_provenance_dir"])
    if len(hosts) == 1:
        r.update(source_provider=hosts[0], state="RESOLVED_FROM_ACQUISITION_WORKER",
                 evidence={"backfilled_provenance_dir": r["source_provenance_dir"], "workers": hits, "url_host": hosts[0]})
    else:
        r.update(source_provider="UNRESOLVED", state="DEFERRED_MISSING_FACT",
                 missing_fact=(f"provenance at {r['source_provenance_dir']} is a documentation backfill; acquisition workers {hits or 'none'} "
                               f"call {'no URL' if not hosts else 'several hosts ' + ','.join(hosts)}: provider not uniquely established"))
rows = doc["rows"]
c = collections.Counter((x["state"], x["source_provider"]) for x in rows)
doc["summary"] = {"files": len(rows), "channels": sum(x["channels"] for x in rows),
                  "resolved_files": sum(x["state"].startswith("RESOLVED") for x in rows),
                  "resolved_channels": sum(x["channels"] for x in rows if x["state"].startswith("RESOLVED")),
                  "deferred_files": sum(not x["state"].startswith("RESOLVED") for x in rows),
                  "deferred_channels": sum(x["channels"] for x in rows if not x["state"].startswith("RESOLVED")),
                  "by_state_provider": {f"{k[0]}|{k[1]}": v for k, v in c.most_common()}}
doc["schema"] = "lane_b_unresolved_resolution.v2"
json.dump(doc, open(OUT, "w"), indent=1)
print(json.dumps(doc["summary"])[:1200])
